#!/usr/bin/env bash
# A bash script that displays the PID, along with the process name, of
# processes whose name contain the word bash
# -l: sees a user's process IDs along with the name of each process
# pgrep: looks through currently running processes


pgrep bash -l
