#!/usr/bin/env bash
# A bash script that displays to infinity and beyond indefinitely
# In between each iteration of the loop, add a sleep 2

while true
do
    echo "To infinity and beyond"
    sleep 2
done
