#!/usr/bin/env bash
# A Bash script displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

for s in {1..100}
do
  if (( s % 3 == 0 && s % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( s % 3 == 0 ))
  then
    echo "Fizz"
  elif (( s % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$s"
  fi
done
